version: "3.1"
# The server profiles used in this example are intended for use with edge versions of the product image only.

#-------------------------------------------------------------------------------------
#- Ping Identity fullstack integrated demo
#-
#-                +----------------+   +----------------+
#-                |   PingAccess   |   |PingDataConsole |
#-                +----------------+   +----------------+
#-
#-                +---------------+    +---------------+
#-                | PingFederate  |    |  PingDataGov  |
#-                +---------------+    +---------------+
#-                              \        /
#-                          +----------------+
#-                          | PingDirectory  |
#-                          +----------------+
#-
#- To view PingAccess Console        | To view PingFederate Console
#-                                   |
#-    https://localhost:9000/        |   https://localhost:9999/pingfederate/app
#-                                   |
#-    Username: administrator        |   Username: administrator
#-    Password: 2FederateM0re        |   Password: 2FederateM0re
#-
#-
#- To view PingData Console (PingDirectory & PingDataGovernance)
#-
#-    https://localhost:8443/
#-
#-      Server: pingdirectory ...or... pingdatagovernance
#-    Username: administrator
#-    Password: 2FederateM0re
#-------------------------------------------------------------------------------------

services:
  pingaccess:
    image: pingidentity/pingaccess:edge
    command: wait-for pingfederate:9031 -t 420 -- entrypoint.sh start-server
    environment: 
      - SERVER_PROFILE_URL=https://github.com/sabbirhussain-ping/UseCases.git
      - SERVER_PROFILE_PATH=ExternalIdPPA/pingaccess
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - .env
    # Example: Examples below for mounting local directories for inbound server profile and persisting
    #          server build.  The local /opt/out directory must be empty when building new server
    #             /opt/out - Resulting server build
    #             /opt/in  - Inbound server-profile detail in liue of SERVER_PROFILE_URL (must be commented out)
    #volumes:
    #   - ${HOME}/projects/devops/volumes/full-stack.pingaccess:/opt/out
    #   - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingaccess:/opt/in
    ports:
      - "443:443"
      - "9000:9000"
    networks:
      - pingnet-dmz

  pingfederate:
    image: pingidentity/pingfederate:2108-10.2.5
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/sabbirhussain-ping/UseCases.git
      - SERVER_PROFILE_PATH=ExternalIdPPA/pingfederate-internal
    env_file:
      - .env
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet-dmz
      - pingnet-internal


  pingfederate-external:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/sabbirhussain-ping/UseCases.git
      - SERVER_PROFILE_PATH=ExternalIdPPA/pingfederate-external
    env_file:
      - .env
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingfederate:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingfederate:/opt/in
    ports:
      - 9032:9031
      - 9998:9999
    networks:
      - pingnet-dmz
      - pingnet-internal

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/sabbirhussain-ping/UseCases.git
      - SERVER_PROFILE_PATH=ExternalIdPPA/pingdirectory
    env_file:
      - .env
    #volumes:
    #  - ${HOME}/projects/devops/volumes/full-stack.pingdirectory:/opt/out
    #  - ${HOME}/projects/devops/pingidentity-server-profiles/baseline/pingdirectory:/opt/in
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1636:636"
      - "1443:443"
      - "1389:389"
    networks:
      - pingnet-internal
  
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - "8443:8443"
    networks: 
      - pingnet-internal

networks:
    pingnet-internal:
    pingnet-dmz:
