global:
  # Your specific environment variables - values are injected into Server Profiles
  envs:
    # Environment Name used in My Ping and Admin Consoles
    ENVIRONMENT_NAME: "Sample-CIAM"
    # Default Administrative Password - passed to APIs as {{globalPwd}}
    # Used for Sample Users and LDAP \ Native Admin accounts
    PING_IDENTITY_PASSWORD: "2FederateM0re"

# PingOne Service Details
pingOne:
  # Set to `true` if you are supplying your PingOne details 
  # C360 leverages PingOne MFA by default
  usePingOneServices: true
  # This configures the proper endpoints for My Ping and PingOne Service IKs
  # PingOne Regions - "NA" | "EU" | "AP"
  envRegion: "NA"
  # If using My Ping - enter the details for the Admin SSO Connection here
  # https://github.com/cprice-ping/Customer360/blob/main/docs/sso-myping.md
  administration:
    # Set to `true` to enable My Ping - if `false`, Admin consoles will use LDAP (PF \ PD) or Native (PC \ PA)
    useMyPing: false
    # Configure these values if `useMyPing` == true
    envId: "YourAdminEnvId"
    adminUserId: "YourAdminUserID" # Not Username - the UUID on the API tab
    logonApp:
      id: "YourAdminApp"
      secret: "YourAdminSecret"
    # Admin Environment's Worker App (Configured in Connections --> Worker) - with AdminUser permissions
    workerApp:
      id: "YourPFWorkerAppID"
      secret: "YourPFWorkerAppSecret"

## Product Specific values
# DevOps Keys and \ or License files can be applied to the container
# License files should be injected into your kubernetes namespace as secrets:
  # (Eval)   ping-devops generate license {product} | kubectl apply -f -
  # (Real)   ping-devops generate license-secret {license file} | kubectl apply -f -
pingdirectory:
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingdirectory


pingdatasync:
  envs:
    SERVER_PROFILE_URL: https://github.com/cprice-ping/Sample-CIAM.git
    SERVER_PROFILE_PATH: pingdatasync